spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_test1
    username: root
    password: card1366
mybatis:
  type-aliases-package: com.itheima.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl